### ISSUE TITLE
UTILS NOT WORKING

### ISSUE THREAD

**Issue by arnavchauhan** [chiphuyen/stanford-tensorflow-tutorials#103]
https://github.com/chiphuyen/stanford-tensorflow-tutorials/blob/54c48f5b694e08b5ceeac17ee84c2bc70bd90f04/examples/03_linreg_dataset.py#L20

Error which I get is: AttributeError: module 'utils' has no attribute 'read_birth_life_data'
Please, help!

**Comment by chiphuyen** [comment]
I don't know what utils you're using. There's 'read_birth_life_data' in [utils.py ](https://github.com/chiphuyen/stanford-tensorflow-tutorials/blob/master/examples/utils.py)
