### ISSUE TITLE
how long is it supposed to run?

### ISSUE THREAD

**Issue by jiteshpabla** [chiphuyen/stanford-tensorflow-tutorials#58]
I left the chatbot.py running in training mode for 2 hours and it's still going, when does it end (if it even does)?

**Comment by ArashHosseini** [comment]
can you tell me please how long its take, my training session is taking about 6 days iter 4373200....

**Comment by MartinAbilev** [comment]
iteration not means anything it just checkpoint   result  of loss index only is what matter !!! run till satisfaction or stop if nothin changes and get diferent model dataset etc..
