### ISSUE TITLE
can't find '/data/mnist'

### ISSUE THREAD

**Issue by jerinw** [chiphuyen/stanford-tensorflow-tutorials#61]

**Comment by LincolnZhuang** [comment]
I guess that code in this tutorial maybe doesn't check whether folder 'data' exists and try to make folder by itself. So try to create folder 'data' where code file is put in and rerun code again.

**Comment by Atlas7** [comment]
Just change it to `./data/mnist` on your local machine, or `data/mnist`. This will work assuming you run the code at `examples` directory.
