### ISSUE TITLE
this line seems does not compile with latest TF

### ISSUE THREAD

**Issue by littlezerg2002** [chiphuyen/stanford-tensorflow-tutorials#71]
https://github.com/chiphuyen/stanford-tensorflow-tutorials/blob/b95dcdf7bd3efa0f6ff3c28e01d3d42d2084b35c/examples/07_convnet_mnist_starter.py#L25

I change it to below to make it pass: 
mnist = input_data.read_data_sets('MNIST_data', one_hot=True)

**Comment by physhik** [comment]
change "/data/mnist" into "data/mnist" 

also change tf.contribute.layers into tf.layers 

and activation_fn -> activation

**Comment by chiphuyen** [comment]
thanks @physhik. also, we'll be releasing the new code for mnist convnet in a few days.
