### ISSUE TITLE
ValueError: Must have exactly one of create/read/write/append mode

### ISSUE THREAD

**Issue by awais786327** [chiphuyen/stanford-tensorflow-tutorials#73]
after changing all 'rb' and 'bw' to 'r' and 'b' it gives the following error

  **File "data.py", line 76, in prepare_dataset
  files.append(open(os.path.join(config.PROCESSED_PATH, filename),'b'))
  ValueError: Must have exactly one of create/read/write/append mode and at most one plus**

does anybody knows? what to do

**Comment by MartinAbilev** [comment]
why still there is 'b' ??   use just  r  and w

    for filename in filenames:
        files.append(open(os.path.join(config.PROCESSED_PATH, filename),'w'))

**Comment by awais786327** [comment]
on replacing 'b' with 'a+'
```
Traceback (most recent call last):
  File "data.py", line 250, in <module>
    prepare_raw_data()
  File "data.py", line 176, in prepare_raw_data
    prepare_dataset(questions, answers)
  File "data.py", line 78, in prepare_dataset
    files[0].write(questions[i] + '\n')
  File "C:\Users\APPBAKERZ-PC\AppData\Local\Programs\Python\Python35\lib\encodin
gs\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\x97' in position 16
8: character maps to <undefined>
```
with 'w'
`
Traceback (most recent call last):
  File "data.py", line 250, in <module>
    prepare_raw_data()
  File "data.py", line 176, in prepare_raw_data
    prepare_dataset(questions, answers)
  File "data.py", line 78, in prepare_dataset
    files[0].write(questions[i] + '\n')
  File "C:\Users\APPBAKERZ-PC\AppData\Local\Programs\Python\Python35\lib\encodin
gs\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\x97' in position 16
8: character maps to <undefined>
`
with 'r'
`
Traceback (most recent call last):
  File "data.py", line 250, in <module>
    prepare_raw_data()
  File "data.py", line 176, in prepare_raw_data
    prepare_dataset(questions, answers)
  File "data.py", line 78, in prepare_dataset
    files[0].write(questions[i] + '\n')
io.UnsupportedOperation: not writable
`

**Comment by sushant097** [comment]
As, i changed as, 
               files.append(open(os.path.join(config.PROCESSED_PATH, filename), 'w'))
and it work. While opening file you should change rb and wb to r and b . That's all!

**Comment by MartinAbilev** [comment]
> Normally, files are opened in text mode, that means, you read and write strings from and to the file, which are encoded in a specific encoding. If encoding is not specified, the default is platform dependent (see open()). 'b' appended to the mode opens the file in binary mode: now the data is read and written in the form of bytes objects. This mode should be used for all files that don’t contain text.  As i remember there no binary files used in this example
