### ISSUE TITLE
matplotlib can't work on Python-2.7.5

### ISSUE THREAD

**Issue by xingjinglu** [chiphuyen/stanford-tensorflow-tutorials#79]
It seems that matplotlib does not work on the old version of python, like 2.7.5. But it works on python 3.6.3.

python2.7/site-packages/six.py", line 82, in _import_module
    __import__(name)
ImportError: No module named Tkinter

And should install active tcl, it works now.
http://www.tkdocs.com/tutorial/install.html

**Comment by chiphuyen** [comment]
Glad to hear that it works now! For the current version of the course, we're using Python 3
