### ISSUE TITLE
mnist_loader for python3

### ISSUE THREAD

**Issue by Adaxry** [chiphuyen/stanford-tensorflow-tutorials#82]
Hello everyone! I find the mnist_loader does't work for python3, so I make following change：
```python
- import cPickle
+ import pickle

def load_data():
    with gzip.open('../data/mnist.pkl.gz', 'rb') as f:
        u = pickle._Unpickler(f)
        u.encoding = 'latin1'
        training_data, validation_data, test_data = u.load()
    return (training_data, validation_data, test_data)
```
Hope to useful for guys.

**Comment by chiphuyen** [comment]
updated with the current version of the code for the course.

**Comment by kakacharles10** [comment]
I got error like:
/floyd/home/network/mnist_loader.py in load_data()
     47         t = pickle._Unpickler(f)
     48         t.encoding = 'latin1'
---> 49         training_data, validation_data, test_data = t.load()
     50 
     51 

/usr/local/lib/python3.6/pickle.py in load(self)
   1048                     raise EOFError
   1049                 assert isinstance(key, bytes_types)
-> 1050                 dispatch[key[0]](self)
   1051         except _Stop as stopinst:
   1052             return stopinst.value

KeyError: 31
