### ISSUE TITLE
module 'utils' has no attribute 'download_mnist', 'read_mnist'

### ISSUE THREAD

**Issue by 645617624** [chiphuyen/stanford-tensorflow-tutorials#94]
After I import utils,  I executed:
mnist_folder = 'data/mnist'
utils.download_mnist(mnist_folder)
train, val, test = utils.read_mnist(mnist_folder, flatten=True)

But
 AttributeError: module 'utils' has no attribute 'read_mnist'
AttributeError: module 'utils' has no attribute 'download_mnist'

You u guys help me with this?
Thanks a lot!

**Comment by chiphuyen** [comment]
You should download utils.py here:
https://github.com/chiphuyen/stanford-tensorflow-tutorials/blob/master/examples/utils.py

**Comment by 645617624** [comment]
Got it!
Thanks a lot Chip!
Shuyue Jia
